# Generated by Django 5.1.6 on 2025-03-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorios', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tittle',
            new_name='nombre_Medicamento',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='presentacion',
        ),
        migrations.AddField(
            model_name='task',
            name='frecuencia',
            field=models.IntegerField(choices=[(6, 'Cada 6 horas'), (8, 'Cada 8 horas'), (12, 'Cada 12 horas'), (24, 'Cada 24 horas')], default=8),
        ),
        migrations.AlterField(
            model_name='task',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
