# Generated by Django 5.1.6 on 2025-03-21 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorios', '0003_rename_tittle_task_nombre_medicamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('dosis', models.IntegerField(default=1)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomas', to='recordatorios.task')),
            ],
        ),
    ]
