# Generated by Django 5.1.6 on 2025-03-21 13:38

import django.db.models.deletion
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('recordatorios', '0003_rename_tittle_task_nombre_medicamento_and_more'), 
    ]

    operations = [
        migrations.AddField(
            model_name='toma',
            name='nueva_hora',
            field=models.DateTimeField(null=True),
        ),
        migrations.RemoveField(
            model_name='toma',
            name='hora',
        ),
        migrations.RenameField(
            model_name='toma',
            old_name='nueva_hora',
            new_name='hora',
        ),
    ]