# Generated by Django 5.1.6 on 2025-03-21 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorios', '0004_toma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialToma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_real', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('tomado', 'Tomado'), ('omitido', 'Omitido')], default='pendiente', max_length=10)),
                ('toma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='recordatorios.toma')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_programada', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('retrasado', 'Retrasado'), ('omitido', 'Omitido')], default='pendiente', max_length=10)),
                ('toma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordatorios.toma')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
