# Generated by Django 5.1.6 on 2025-03-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorios', '0007_toma_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesada', 'Procesada')], default='pendiente', max_length=10),
        ),
    ]
