# Generated by Django 5.1.6 on 2025-03-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorios', '0010_alter_toma_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toma',
            name='hora',
            field=models.DateTimeField(),
        ),
    ]
