# Generated by Django 5.1.6 on 2025-04-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorios', '0012_alter_toma_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='presentacion',
            field=models.CharField(max_length=100),
        ),
    ]
